#!/bin/bash
# =============================================================================
# Expiration Reminder - Oracle Linux Deployment Script
# =============================================================================
# Usage:
#   ./deploy.sh                     # Install/update in default directory
#   ./deploy.sh /custom/path        # Install in a custom directory
#
# The schedule is controlled by RUN_TIME in your .env file (default: 08:00).
# =============================================================================

set -e

APP_DIR="${1:-/opt/expiration-reminder}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --------------------------------------------------------------------------
# Helper
# --------------------------------------------------------------------------
info()  { echo "[INFO]  $*"; }
ok()    { echo "[OK]    $*"; }
err()   { echo "[ERROR] $*" >&2; exit 1; }

# --------------------------------------------------------------------------
# 1. Read RUN_TIME from .env (format HH:MM, default 08:00)
# --------------------------------------------------------------------------
ENV_FILE="$SCRIPT_DIR/.env"
[[ -f "$ENV_FILE" ]] || err ".env file not found in $SCRIPT_DIR — copy .env.example to .env and fill in your values."

RUN_TIME=$(grep -E '^RUN_TIME=' "$ENV_FILE" | cut -d'=' -f2 | tr -d '"' | tr -d "'" | tr -d '[:space:]')
RUN_TIME="${RUN_TIME:-08:00}"

RUN_HOUR="${RUN_TIME%%:*}"
RUN_MIN="${RUN_TIME##*:}"

# Validate format
[[ "$RUN_HOUR" =~ ^[0-9]{1,2}$ && "$RUN_MIN" =~ ^[0-9]{2}$ ]] \
    || err "Invalid RUN_TIME format '$RUN_TIME'. Expected HH:MM (e.g. 08:00)."

info "Schedule: every day at $RUN_TIME (cron: $RUN_MIN $RUN_HOUR * * *)"

# --------------------------------------------------------------------------
# 2. Check / install Python 3
# --------------------------------------------------------------------------
if ! command -v python3 &>/dev/null; then
    info "Python 3 not found — installing via dnf..."
    sudo dnf install -y python3 python3-pip
else
    ok "Python 3 found: $(python3 --version)"
fi

# --------------------------------------------------------------------------
# 3. Copy application files to APP_DIR
# --------------------------------------------------------------------------
info "Deploying to $APP_DIR ..."
sudo mkdir -p "$APP_DIR"
sudo rsync -a --exclude='.git' --exclude='venv' --exclude='__pycache__' \
    "$SCRIPT_DIR/" "$APP_DIR/"

# --------------------------------------------------------------------------
# 4. Set up virtual environment and install dependencies
# --------------------------------------------------------------------------
info "Setting up virtual environment..."
sudo python3 -m venv "$APP_DIR/venv"
sudo "$APP_DIR/venv/bin/pip" install --upgrade pip --quiet
sudo "$APP_DIR/venv/bin/pip" install -r "$APP_DIR/requirements.txt" --quiet
ok "Dependencies installed."

# --------------------------------------------------------------------------
# 5. Permissions
# --------------------------------------------------------------------------
sudo chmod +x "$APP_DIR/run.sh"
# Restrict .env and credentials (readable only by root / the running user)
sudo chmod 600 "$APP_DIR/.env"
sudo chmod 600 "$APP_DIR"/*.json 2>/dev/null || true

# --------------------------------------------------------------------------
# 6. Install cron job  (/etc/cron.d — runs as root by default)
# --------------------------------------------------------------------------
CRON_FILE="/etc/cron.d/expiration-reminder"
CRON_LOG="$APP_DIR/app.log"

info "Writing cron job to $CRON_FILE ..."
sudo tee "$CRON_FILE" > /dev/null <<EOF
# Expiration Reminder — auto-generated by deploy.sh
# Schedule controlled by RUN_TIME in $APP_DIR/.env
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

$RUN_MIN $RUN_HOUR * * * root cd $APP_DIR && $APP_DIR/run.sh >> $CRON_LOG 2>&1
EOF

sudo chmod 644 "$CRON_FILE"
ok "Cron job installed: runs daily at $RUN_TIME."

# --------------------------------------------------------------------------
# 7. Quick smoke-test (dry run — just check imports)
# --------------------------------------------------------------------------
info "Running smoke test..."
if sudo "$APP_DIR/venv/bin/python" -c "import gspread, oauth2client, dotenv, requests" 2>&1; then
    ok "All dependencies importable."
else
    err "Smoke test failed — check the virtualenv and requirements.txt."
fi

# --------------------------------------------------------------------------
# Done
# --------------------------------------------------------------------------
echo ""
echo "============================================================"
echo "  Deployment complete!"
echo "  App directory : $APP_DIR"
echo "  Schedule      : every day at $RUN_TIME"
echo "  Log file      : $CRON_LOG"
echo ""
echo "  To run manually:"
echo "    sudo $APP_DIR/run.sh"
echo ""
echo "  To change the schedule:"
echo "    Edit RUN_TIME in $APP_DIR/.env, then re-run deploy.sh"
echo "============================================================"
